services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 order_system.wsgi:application

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: 1234
      PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: