# Generated by Django 4.2.19 on 2025-02-24 13:34

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[orders.models.valid_quantity_is_zero], verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='created', max_length=15, verbose_name='Статус'),
        ),
    ]
