services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 order_system.wsgi:application

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
    volumes:
      - static_volume:/app/static
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_NAME_DB}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: